--- simirian's Neovim
--- generic picker library

local async = require("async")

--- The list of items which were generated by the bound picker.
--- @type any[]
local generated

--- The list of items which were sorted by the bound picker.
--- @type any[]
local sorted

--- The index of the selected item.
--- @type integer
local selected

--- Sorts the items which are being picked over.
--- @param items any[] The items to sort.
--- @param prompt string The user's current prompt.
--- @return any[]
local function sort(items, prompt) --- @diagnostic disable-line: unused-local
  return items
end

--- Converts the given item into a string.
--- @param item any The item to display.
--- @param idx integer The index of the item.
--- @return string
local function display(item, idx) --- @diagnostic disable-line: unused-local
  return tostring(item)
end

--- Called to obtain the preview of a particular item. The function must
--- populate the window with a preview of the item.
--- @param item any The item to display.
--- @param idx integer The index of the item.
--- @param winid integer The window id to put the preview in.
local function preview(item, idx, winid) --- @diagnostic disable-line: unused-local
end

--- Converts the given item to a quickfix list entry.
--- @param item any The item to convert.
--- @param idx integer The index of the item.
--- @return vim.quickfix.entry
local function toquickfix(item, idx) --- @diagnostic disable-line: unused-local
  return { filename = "", lnum = 1, text = "UNKNOWN" }
end

--- Does something with the item after the user selects it.
--- @param item any The item to do somehting with.
--- @param idx integer The index of the item.
local function confirm(item, idx) end --- @diagnostic disable-line: unused-local

--- Does something when the picker is closed without confirmation.
local function cancel() end

--- Buffer used for input.
--- @type integer
local ibuf = vim.api.nvim_create_buf(false, true)
vim.api.nvim_buf_set_name(ibuf, "Pick Input")

--- Buffer used for listing.
--- @type integer
local lbuf = vim.api.nvim_create_buf(false, true)
vim.api.nvim_buf_set_name(lbuf, "Pick List")

--- Buffer used for previews.
--- @type integer
local pbuf = vim.api.nvim_create_buf(false, true)
vim.api.nvim_buf_set_name(pbuf, "Pick Preview")

--- The window used to display the input buffer.
--- @type integer?
local iwin

--- The window used to display the list buffer.
--- @type integer?
local lwin

--- The window used to display the preview.
--- @type integer?
local pwin

--- Opens the picker windows.
local function openwins()
  local base = {
    relative = "editor",
    border = "solid",
    style = "minimal",
  }
  local top = math.floor(vim.o.lines / 10)
  local right = math.floor(vim.o.columns / 10)
  local fullwidth = math.floor(vim.o.columns * 8 / 10)
  local fullheight = math.floor(vim.o.lines * 8 / 10) - 2
  iwin = vim.api.nvim_open_win(ibuf, true, vim.tbl_deep_extend("force", base, {
    row = top,
    col = right,
    width = preview and math.floor(fullwidth / 2) - 2 or fullwidth - 2,
    height = 1,
  }))
  vim.wo[iwin].winhighlight = "NormalFloat:PickInput,FloatBorder:PickInput"
  vim.wo[iwin].statuscolumn = "%#PickInput#   "
  lwin = vim.api.nvim_open_win(lbuf, false, vim.tbl_deep_extend("force", base, {
    row = top + 3,
    col = right,
    width = preview and math.floor(fullwidth / 2) - 2 or fullwidth - 2,
    height = fullheight - 5,
    focusable = false,
  }))
  vim.wo[lwin].cursorline = true
  vim.wo[lwin].winhighlight = "NormalFloat:PickList,FloatBorder:PickList,CursorLine:Search"
  if preview then
    pwin = vim.api.nvim_open_win(pbuf, false, vim.tbl_deep_extend("force", base, {
      row = top,
      col = right + math.floor(fullwidth / 2),
      width = math.floor(fullwidth / 2) - 2,
      height = fullheight - 2,
    }))
    vim.wo[pwin].winhighlight = "NormalFloat:PickList,FloatBorder:PickList"
  end
end

--- Closes the picker windows.
local function closewins()
  if iwin then
    vim.api.nvim_win_close(iwin, true)
    iwin = nil
  end
  if lwin then
    vim.api.nvim_win_close(lwin, true)
    lwin = nil
  end
  if pwin then
    vim.api.nvim_win_close(pwin, true)
    pwin = nil
  end
  vim.api.nvim_buf_set_lines(ibuf, 0, -1, false, { "" })
end

--- Selects an item and updates the preview and the list.
--- @param idx integer The index of the selection.
local function selectitem(idx)
  selected = idx
  if lwin then
    local winheight = vim.api.nvim_win_get_height(lwin)
    local first = math.max(selected - winheight, 1)
    local last = math.min(selected + winheight, #sorted)
    local lines = vim.api.nvim_buf_get_lines(lbuf, first - 1, last, false)
    for i, line in ipairs(lines) do
      if line == "" then
        lines[i] = display(sorted[i + first - 1], i + first - 1)
      end
    end
    vim.bo[lbuf].modifiable = true
    vim.api.nvim_buf_set_lines(lbuf, first - 1, last, false, lines)
    vim.bo[lbuf].modifiable = false
    vim.api.nvim_win_set_cursor(lwin, { selected, 0 })
  end
  vim.api.nvim_buf_set_lines(pbuf, 0, -1, false, {})
  if pwin then
    vim.api.nvim_win_set_buf(pwin, pbuf)
    if preview and sorted[idx] ~= nil then
      -- WHY DOES THIS NEED TO BE SCHEDULED SOMETIMES???? It's not even always.
      -- When this wasn't scheduled, the :edit command worked in the grep
      -- picker but not the files picker for some reason. The normal
      -- autocommands for reading files were being skipped in only that case for
      -- some reason. This took like three hours to debug :(
      vim.schedule(function()
        preview(sorted[idx], idx, pwin)
      end)
    end
  end
end

--- @type Async
local agenthread

--- @type Async
local asortthread

--- Runs the picker sorter on the generated items asynchronously.
local function asort()
  if not generated then return end
  if asortthread then asortthread:abort() end
  asortthread = async(function()
    local line = vim.api.nvim_buf_get_lines(ibuf, -2, -1, false)[1]
    return sort(generated, line)
  end):done(function(items)
    sorted = items
    vim.bo[lbuf].modifiable = true
    vim.api.nvim_buf_set_lines(lbuf, 0, -1, false, vim.tbl_map(function() return "" end, sorted))
    vim.bo[lbuf].modifiable = false
    selectitem(1)
  end)
  asortthread:run()
end

--- Runs the bound picker generator asynchronously.
--- @param fn fun(): any[] Function to generate the list of items.
local function agen(fn)
  if agenthread then agenthread:abort() end
  generated = {}
  agenthread = async(function()
    return fn()
  end):done(function(items)
    generated = items
    asort()
  end)
  agenthread:run()
end

--- Closes the picker.
local function close()
  closewins()
  if agenthread then agenthread:abort() end
  if asortthread then asortthread:abort() end
end

--- The auroup used by this plugin.
--- @type integer
local augroup = vim.api.nvim_create_augroup("pick", { clear = true })

vim.api.nvim_create_autocmd({ "TextChangedI", "TextChanged" }, {
  desc = "Update picker item list.",
  group = augroup,
  buffer = ibuf,
  callback = function () if iwin then asort() end end,
})

vim.api.nvim_create_autocmd("BufEnter", {
  desc = "Enter insert mode when entering the input buffer.",
  group = augroup,
  buffer = ibuf,
  callback = function()
    vim.cmd.startinsert()
    vim.api.nvim_win_set_cursor(0, {
      vim.api.nvim_win_get_cursor(0)[1],
      #vim.api.nvim_get_current_line()
    })
  end,
})

vim.api.nvim_create_autocmd("BufLeave", {
  desc = "Leave insert when leaving input buffer.",
  group = augroup,
  buffer = ibuf,
  callback = function()
    vim.cmd.stopinsert()
  end,
})

vim.api.nvim_create_autocmd("WinClosed", {
  desc = "Close picker when one of the picker windows closes.",
  group = augroup,
  callback = function(e)
    local id = tonumber(e.file) or 0
    if id == iwin or id == lwin or id == pwin then
      close()
      cancel()
    end
  end,
})

vim.keymap.set({ "i", "n" }, "<cr>", function()
  cancel = function() end
  close()
  confirm(sorted[selected], selected)
end, { desc = "Confirm picker selection.", buffer = ibuf })

vim.keymap.set("n", "<esc>", function()
  local win = vim.api.nvim_get_current_win()
  if win == iwin or win == pwin then
    close()
  end
end, { desc = "Close the picker with escape in normal mode." })

vim.keymap.set({ "i", "n" }, "<C-n>", function()
  selectitem(selected == #sorted and 1 or selected + 1)
end, { desc = "Select next item in list.", buffer = ibuf })

vim.keymap.set({ "i", "n" }, "<C-p>", function()
  selectitem(selected == 1 and #sorted or selected - 1)
end, { desc = "Select previous item in list.", buffer = ibuf })

vim.keymap.set("n", "<C-^>", function()
  local win = vim.api.nvim_get_current_win()
  if win == iwin and pwin then
    vim.schedule(function()
      vim.api.nvim_tabpage_set_win(0, pwin)
    end)
    return ""
  elseif win == pwin and iwin then
    vim.schedule(function()
      vim.api.nvim_tabpage_set_win(0, iwin)
    end)
    return ""
  end
  return "<C-6>"
end, { desc = "Switch between preview and input buffers.", expr = true })

vim.keymap.set({ "i", "n" }, "<C-q>", function()
  if not toquickfix then return end
  local items = {}
  for idx, item in ipairs(sorted) do
    table.insert(items, toquickfix(item, idx))
  end
  vim.fn.setqflist(items)
  close()
  vim.cmd.cope()
end, { desc = "Send the current sorted list to the quickfix list.", buffer = ibuf })

local M = {}

--- Filters/sorts selections based on mini.nvim's pick module, but also forces
--- fuzzy matching if the first character is a space, and ignores that space.
--- Uses the above fuzz() function as a fallback for when there isn't a prefix.
--- @param list (string|table)[] The list to be filtered.
--- @param query string The query to use to filter the list.
--- @param field string Field of the list items to sort on.
--- @return string[]
function M.match(list, query, field)
  local function pmatch(i, q)
    coroutine.yield()
    local str = field and i[field] or i
    local ok, found = pcall(string.match, str, q)
    return ok and found ~= nil
  end
  if query == "" then return list end
  local neg = query:sub(1, 1) == "!"
  local mode = neg and query:sub(2, 2) or query:sub(1, 1)
  local predicates = {
    ["'"] = function(e) return pmatch(e, query) ~= neg end,
    ["^"] = function(e) return pmatch(e, "^" .. query) ~= neg end,
    ["$"] = function(e) return pmatch(e, query .. "$") ~= neg end,
  }
  if predicates[mode] then
    query = query:sub(neg and 3 or 2)
    return vim.tbl_filter(predicates[mode], list)
  else
    query = query:sub(1, 1) == " " and query:sub(2) or query
    local dict = vim.empty_dict()
    dict.key = field
    return vim.fn.matchfuzzy(list, query, dict)
  end
end

--- The arguments required to set up a new picker.
--- @class Pick.Args<T>
--- A list of items to pick from, or a function to generate them in an async
--- context. If a function, then `coroutine.yield()` may be used freely.
--- @field list T[] | fun(): T[]
--- The function used to sort the items in the list based on the user's prompt.
--- The function is called in an async context, so `coroutine.yield()` may be
--- used freely.
--- @field sort fun(items: T[], prompt: string): T[]
--- The function used to convert each item to a string for display. Default
--- value is `tostring()`.
--- @field display? fun(item: T, idx: integer): string
--- The function used to populate the preview window. This function is expected
--- to put something in the preview window, but there is no prior expectation as
--- to what that thing is. The window is pre-populated with an empty dummy
--- buffer whose lines can be set.
--- @field preview? fun(item: T, idx: integer, winid: integer)
--- Function which can move entries to the quickfix list.
--- @field toquickfix? fun(item: T, idx: integer): vim.quickfix.entry
--- Callback for when the user confirms their selection.
--- @field confirm fun(item: T, idx: integer)
--- Callback for when the picker is cancelled or ended by any means which isn't
--- cancellation.
--- @field cancel? fun()

--- Adds a new picker to the picker list.
--- @param args Pick.Args The picker variables.
function M.pick(args)
  display = args.display or tostring
  preview = args.preview
  toquickfix = args.toquickfix
  confirm = args.confirm or function() end
  cancel = args.cancel or function() end
  openwins()
  if type(args.list) == "function" then
    agen(args.list --[[@as fun(): any[] ]])
  else
    generated = args.list --[[@as any[] ]] or {}
  end
  sort = args.sort or function(items) return items end
  if type(args.list) ~= "function" then
    asort()
  end
end

function M.cancel()
  close()
end

return M
