--- simirian's Neovim
--- generic picker plugin

local async = require("async")

--- The list of items which were generated by the bound picker.
--- @type any[]
local generated

--- The list of items which were sorted by the bound picker.
--- @type any[]
local sorted

--- The index of the selected item.
--- @type integer
local selected

--- Sorts the items which are being picked over.
--- @param items any[] The items to sort.
--- @param prompt string The user's current prompt.
--- @return any[]
local function sort(items, prompt) --- @diagnostic disable-line: unused-local
  return items
end

--- Converts the given item into a string.
--- @param item any The item to display.
--- @param idx integer The index of the item.
--- @return string
local function display(item, idx) --- @diagnostic disable-line: unused-local
  return tostring(item)
end

--- Converts the given item to a quickfix list entry.
--- @param item any The item to convert.
--- @param idx integer The index of the item.
--- @return vim.quickfix.entry
local function toquickfix(item, idx) --- @diagnostic disable-line: unused-local
  return { filename = "", lnum = 1, text = "UNKNOWN" }
end

--- Does something with the item after the user selects it.
--- @param item any The item to do somehting with.
--- @param idx integer The index of the item.
local function confirm(item, idx) --- @diagnostic disable-line: unused-local
end

--- Buffer used for input.
--- @type integer
local ibuf = vim.api.nvim_create_buf(false, true)
vim.api.nvim_buf_set_name(ibuf, "Pick Input")

--- Buffer used for listing.
--- @type integer
local lbuf = vim.api.nvim_create_buf(false, true)
vim.api.nvim_buf_set_name(lbuf, "Pick List")

--- The window used to display the input buffer.
--- @type integer?
local iwin

--- The window used to display the list buffer.
--- @type integer?
local lwin

--- Opens the picker windows.
local function openwins()
  local base = {
    relative = "editor",
    border = "solid",
    style = "minimal",
  }
  iwin = vim.api.nvim_open_win(ibuf, true, vim.tbl_deep_extend("force", base, {
    row = math.floor(vim.o.lines / 10),
    col = math.floor(vim.o.columns / 10),
    height = 1,
    width = math.floor(vim.o.columns * 8 / 10),
  }))
  vim.wo[iwin].winhighlight = "NormalFloat:PickInput,FloatBorder:PickInput"
  vim.wo[iwin].statuscolumn = "%#PickInput#   "
  lwin = vim.api.nvim_open_win(lbuf, false, vim.tbl_deep_extend("force", base, {
    row = math.floor(vim.o.lines / 10 + 3),
    col = math.floor(vim.o.columns / 10),
    width = math.floor(vim.o.columns * 8 / 10),
    height = math.floor(vim.o.lines * 8 / 10 - 5),
  }))
  vim.wo[lwin].cursorline = true
  vim.wo[lwin].winhighlight = "NormalFloat:PickList,FloatBorder:PickList,CursorLine:Search"
end

--- Closes the picker windows.
local function closewins()
  if iwin then
    vim.api.nvim_win_close(iwin, true)
    iwin = nil
  end
  if lwin then
    vim.api.nvim_win_close(lwin, true)
    lwin = nil
  end
  vim.api.nvim_buf_set_lines(ibuf, 0, -1, false, { "" })
end

--- Renders only the lines which could be visible, instead of all lines.
local function displayframe()
  if not lwin then return end
  local winheight = vim.api.nvim_win_get_height(lwin)
  local first = math.max(selected - winheight, 1)
  local last = math.min(selected + winheight, #sorted)
  local lines = vim.api.nvim_buf_get_lines(lbuf, first - 1, last, false)
  for i, line in ipairs(lines) do
    if line == "" then
      lines[i] = display(sorted[i + first - 1], i + first - 1)
    end
  end
  vim.bo[lbuf].modifiable = true
  vim.api.nvim_buf_set_lines(lbuf, first - 1, last, false, lines)
  vim.bo[lbuf].modifiable = false
  vim.api.nvim_win_set_cursor(lwin, { selected, 0 })
end

--- @type Async
local agenthread

--- @type Async
local asortthread

--- Runs the picker sorter on the generated items asynchronously.
local function asort()
  if not generated then return end
  if asortthread then asortthread:abort() end
  asortthread = async(function()
    local line = vim.api.nvim_buf_get_lines(ibuf, -2, -1, false)[1]
    return sort(generated, line)
  end):done(function(items)
    sorted, selected = items, 1
    vim.bo[lbuf].modifiable = true
    vim.api.nvim_buf_set_lines(lbuf, 0, -1, false, vim.tbl_map(function() return "" end, sorted))
    vim.bo[lbuf].modifiable = false
    displayframe()
  end)
  asortthread:run()
end

--- Runs the bound picker generator asynchronously.
--- @param fn fun(): any[] Function to generate the list of items.
local function agen(fn)
  if agenthread then agenthread:abort() end
  generated = {}
  agenthread = async(function()
    return fn()
  end):done(function(items)
    generated = items
    asort()
  end)
  agenthread:run()
end

--- Opens the picker.
local function open()
  openwins()
  displayframe()
end

--- Closes the picker.
local function close()
  closewins()
  if agenthread then agenthread:abort() end
  if asortthread then asortthread:abort() end
end

--- The auroup used by this plugin.
--- @type integer
local augroup = vim.api.nvim_create_augroup("pick", { clear = true })

vim.api.nvim_create_autocmd({ "TextChangedI", "TextChanged" }, {
  desc = "Update picker item list.",
  group = augroup,
  buffer = ibuf,
  callback = function () if iwin then asort() end end,
})

vim.api.nvim_create_autocmd("BufEnter", {
  desc = "Enter insert mode when entering the input buffer.",
  group = augroup,
  buffer = ibuf,
  callback = function()
    vim.cmd.startinsert()
    vim.api.nvim_win_set_cursor(0, {
      vim.api.nvim_win_get_cursor(0)[1],
      #vim.api.nvim_get_current_line()
    })
  end,
})

vim.api.nvim_create_autocmd("BufLeave", {
  desc = "Close picker when leaving the input buffer.",
  group = augroup,
  buffer = ibuf,
  callback = function()
    close()
    vim.cmd.stopinsert()
  end,
})

vim.keymap.set({ "i", "n" }, "<cr>", function()
  close()
  confirm(sorted[selected], selected)
end, { desc = "Confirm picker selection.", buffer = ibuf })

vim.keymap.set("n", "<esc>", function()
  close()
end, { desc = "Close the picker.", buffer = ibuf })

vim.keymap.set({ "i", "n" }, "<C-n>", function()
  selected = selected == #sorted and 1 or selected + 1
  displayframe()
end, { desc = "Select next item in list.", buffer = ibuf })

vim.keymap.set({ "i", "n" }, "<C-p>", function()
  selected = selected == 1 and #sorted or selected - 1
  displayframe()
end, { desc = "Select previous item in list.", buffer = ibuf })

vim.keymap.set({ "i", "n" }, "<C-q>", function()
  if not toquickfix then return end
  local items = {}
  for idx, item in ipairs(sorted) do
    table.insert(items, toquickfix(item, idx))
  end
  vim.fn.setqflist(items)
  closewins()
  vim.cmd.cope()
end, { desc = "Send the current sorted list to the quickfix list.", buffer = ibuf })

--- Scores a string based on how well it matches a query. UPDATED! I wrote the
--- new version in an hour as well, but after taking a bioinformatics class and
--- learning about sequence alignment :P This is slower: O(NM), but still likely
--- fast enough most people.
--- @param item string The item to score.
--- @param query string The query to score based on.
local function score(item, query)
  local match = 1 -- initial match
  local continue = 1.5 -- subsequent matches
  local mismatch = -1.2 -- mismatched query and item
  local startskip = -0.2 -- skipped start of item
  local strskip = -0.5 -- skipped middle part of item
  local endskip = -0.1 -- skipped terminal part of item
  local qryskip = -1 -- skipped query character
  local qryfail = -2 -- failed to complete query

  local sl = #item
  local ql = #query

  local scores = { { 0 } }
  local types = { { false } }

  for col = 2, sl + 1 do
    scores[1][col] = scores[1][col - 1] + startskip
    types[1][col] = false
  end

  for row = 2, ql + 1 do
    local psrow = scores[row - 1]
    local ptrow = types[row - 1]
    local srow = { psrow[1] + qryskip }
    local trow = { false }
    for col = 2, sl + 1 do
      -- score coming from above
      local s = psrow[col] + (col == sl and qryfail or qryskip)
      local t = false

      -- score coming from left
      local ls = srow[col - 1]
      if row == ql + 1 then
        ls = ls + endskip
      else
        ls = ls + strskip
      end
      if ls > s then
        s = ls
      end

      -- score coming from the diagonal
      local ds = psrow[col - 1]
      local m = item:sub(col - 1, col - 1) == query:sub(row - 1, row - 1)
      if not m then
        ds = ds + mismatch
      elseif ptrow[col - 1] then
        ds = ds + continue
      else
        ds = ds + match
      end
      if ds > s then
        s = ds
        t = m and true or false
      end

      srow[col] = s
      trow[col] = t
    end
    scores[row] = srow
    types[row] = trow
  end
  return scores[ql + 1][sl + 1]
end

--- Simple fuzzy finding algorithm.
--- @param list string[] List of strings to score.
--- @param query string The query string to score based on.
--- @return string[]
local function fuzz(list, query)
  local plist = {}
  local pause = 0
  -- initial filter
  plist = vim.tbl_filter(function(str)
    if pause % 100 == 0 then
      coroutine.yield()
    end
    pause = pause + 1
    local l = 0
    local si = 1
    local slow = str:lower()
    local th = #query * .75
    for qi = 1, #query do
      local i = slow:find(query:sub(qi, qi):lower(), si, true)
      if i then
        si = i
      else
        l = l + 1 + #query - qi
        if l > th then return false end
      end
    end
    return true
  end, list)
  -- score strings
  plist = vim.tbl_map(function(str)
    if pause % 100 == 0 then
      coroutine.yield()
    end
    pause = pause + 1
    return { str, score(str, query) }
  end, plist)
  -- sort by scores
  table.sort(plist, function(a, b) return a[2] > b[2] end)
  -- select the string and return it
  return vim.tbl_map(function(e) return e[1] end, plist)
end

--- Filters/sorts selections based on mini.nvim's pick module, but also forces
--- fuzzy matching if the first character is a space, and ignores that space.
--- Uses the above fuzz() function as a fallback for when there isn't a prefix.
--- @param list string[] The list to be filtered.
--- @param query string The query to use to filter the list.
--- @return string[]
local function match(list, query)
  local function pmatch(s, q)
    coroutine.yield()
    local ok, found = pcall(string.match, s, q)
    return ok and found ~= nil
  end
  if query == "" then return list end
  local neg = query:sub(1, 1) == "!"
  local mode = neg and query:sub(2, 2) or query:sub(1, 1)
  local predicates = {
    ["'"] = function(e) return pmatch(e, query) ~= neg end,
    ["^"] = function(e) return pmatch(e, "^" .. query) ~= neg end,
    ["$"] = function(e) return pmatch(e, query .. "$") ~= neg end,
  }
  if predicates[mode] then
    query = query:sub(neg and 3 or 2)
    return vim.tbl_filter(predicates[mode], list)
  else
    if query:sub(1, 1) == " " then
      return fuzz(list, query:sub(2))
    else
      return fuzz(list, query)
    end
  end
end

local M = {}

--- The arguments required to set up a new picker.
--- @class Pick.Args<T>
--- A list of items to pick from, or a function to generate them in an async
--- context. If a function, then `coroutine.yield()` may be used freely.
--- @field list T[] | fun(): T[]
--- The function used to sort the items in the list based on the user's prompt.
--- The function is called in an async context, so `coroutine.yield()` may be
--- used freely.
--- @field sort fun(items: T[], prompt: string): items: T[]
--- The function used to convert each item to a string for display. Default
--- value is `tostring()`.
--- @field display? fun(item: T, idx: integer): string
--- Function which can move entries to the quickfix list.
--- @field toquickfix? fun(item: T, idx: integer): vim.quickfix.entry
--- Callback for when the user confirms their selection.
--- @field confirm fun(item: T, idx: integer)

--- Adds a new picker to the picker list.
--- @param args Pick.Args The picker variables.
function M.pick(args)
  if type(args.list) == "function" then
    agen(args.list --[[@as fun(): any[] ]])
  else
    generated = args.list --[[@as any[] ]]
  end
  sort = args.sort or function(items) return items end
  if type(args.list) ~= "function" then
    asort()
  end
  display = args.display or tostring
  toquickfix = args.toquickfix
  confirm = args.confirm or function() end
  open()
end

--- Prompt user to select an item from a list.
--- @generic T
--- @param list T[]
--- @param opts vim.ui.select.Opts
--- @param on_choice fun(item: T, idx: integer)
--- @diagnostic disable-next-line: duplicate-set-field
vim.ui.select = function(list, opts, on_choice)
  M.pick({
    list = list,
    sort = match,
    display = opts.format_item or tostring,
    confirm = on_choice,
  })
end

--- Opens a picker prompt whose input is forwarded to ripgrep.
function M.grep()
  -- set callbacks
  sort = function(_, prompt)
    local out = async.system({ "rg", "--vimgrep", "-Se", prompt == "" and ".*" or prompt }, {})
    if not out then return {} end
    if out.code == 0 then
      return vim.split(out.stdout, "[\r\n]+", { trimempty = true })
    else
      return {}
    end
  end
  display = tostring
  toquickfix = function(item)
    local name, line, col = item:match("^([^:]+):(%d+):(%d+):.*$")
    return { filename = name, lnum = line, col = col }
  end
  confirm = function(item)
    local name, line, col = item:match("^([^:]+):(%d+):(%d+):.*$")
    if name and line and col then
      vim.cmd.edit(name)
      vim.api.nvim_win_set_cursor(0, { tonumber(line), tonumber(col) })
    end
  end
  open()
end

--- Opens a picker prompt for help tags.
function M.help()
  agen(function()
    local tags = {}
    local files = vim.api.nvim_get_runtime_file("doc/tags", true)
    for _, file in ipairs(files) do
      local fd = vim.uv.fs_open(file, "r", 420)
      if not fd then return {} end
      local size = vim.uv.fs_fstat(fd).size
      local contents = vim.uv.fs_read(fd, size)
      vim.uv.fs_close(fd)
      if not contents then return {} end
      for tag in contents:gmatch("([^\r\n\t]+)[^\r\n]+") do
        table.insert(tags, tag)
      end
    end
    return tags
  end)
  -- set callbacks
  sort = match
  display = tostring
  toquickfix = nil --- @diagnostic disable-line: cast-local-type
  confirm = function(item) vim.cmd.help(item) end
  open()
end

--- Pick from all files in the current directory excluding git files.
function M.files()
  agen(function()
    local function lsr(path)
      local strs = {}
      for name, type in vim.fs.dir(path) do
        if name ~= ".git" or type ~= "directory" then
          coroutine.yield()
          local fname = path .. "/" .. name
          table.insert(strs, fname)
          if type == "directory" then
            vim.list_extend(strs, lsr(fname))
          end
        end
      end
      return strs
    end
    return vim.tbl_map(function(s) return s:sub(3) end, lsr("."))
  end)
  -- set callbacks
  sort = match
  display = tostring
  toquickfix = function(item) return { filename = item } end
  confirm = function(item) vim.cmd.edit(item) end
  open()
end

--- Opens a picker for listed vim buffers.
function M.buffers()
  local bufnrs = vim.api.nvim_list_bufs()
  local listed = vim.tbl_filter(function(bufnr) return vim.fn.buflisted(bufnr) == 1 end, bufnrs)
  local names = vim.tbl_map(vim.api.nvim_buf_get_name, listed)
  M.pick({
    list = names,
    sort = match,
    display = function(item) return vim.fn.fnamemodify(item, ":~:.") end,
    toquickfix = function(item) return { bufnr = vim.fn.bufnr(item), } end,
    confirm = function(bufname) vim.cmd.buffer(bufname) end,
  })
end

--- Picks across quickfix items.
function M.quickfix()
  --- @type vim.quickfix.entry[]
  local items = vim.fn.getqflist()
  M.pick({
    list = items,
    sort = match,
    display = function(item)
      return item.text ~= "" and item.text
          or vim.fn.fnamemodify(vim.api.nvim_buf_get_name(item.bufnr), ":~:.")
    end,
    toquickfix = function(item) return item end,
    confirm = function(item)
      vim.cmd.buffer(item.bufnr)
      vim.api.nvim_win_set_cursor(0, { item.lnum + 1, item.col })
    end,
  })
end

vim.api.nvim_create_user_command("Pick", function(args)
  if M[args.args] then
    M[args.args]()
  end
end, {
  desc = "Use a picker.",
  nargs = "?",
  bang = true,
  complete = function(arglead, cmdline, curpos)
    if curpos ~= #cmdline then return end
    return vim.tbl_filter(function(e)
      return vim.startswith(e, arglead)
    end, vim.tbl_keys(M))
  end,
})

vim.keymap.set("n", "<leader>ff", M.files, { desc = "Find files." })
vim.keymap.set("n", "<leader>fh", M.help, { desc = "Find help." })
vim.keymap.set("n", "<leader>fg", M.grep, { desc = "Find with grep." })
vim.keymap.set("n", "<leader>fb", M.buffers, { desc = "Find buffers." })

package.loaded["pick"] = M
